# Generated by Django 5.2.7 on 2025-10-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_full_name'),
        ),
    ]
