# Generated by Django 5.2.7 on 2025-10-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turns_score', models.FloatField(default=None, null=True)),
                ('air_score', models.FloatField(default=None, null=True)),
                ('time_score', models.FloatField(default=None, null=True)),
                ('total_score', models.FloatField(default=None, null=True)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
