# Generated by Django 5.2.7 on 2025-10-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_air_score_alter_score_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='total_score',
        ),
    ]
