# Generated by Django 5.2.7 on 2025-10-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_remove_score_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='air_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='time_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='turns_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
    ]
