# Generated by Django 5.2.7 on 2025-10-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
        ('participants', '0002_alter_participant_options_and_more'),
        ('scores', '0004_alter_score_air_score_alter_score_time_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['event'], name='event_index'),
        ),
    ]
